config/routes.rb
Rails.application.routes.draw do
  resources :ui_components
  resources :websites
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "websites#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  class << self
    def admin_role
      where(name: "admin").first
    end
  end
end

app/models/ui_component.rb
class UiComponent < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :websites
  has_many :user_roles

  def admin?
    user_roles.where(role: Role.admin_role).any?
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :role
  belongs_to :user
end

app/models/website.rb
class Website < ApplicationRecord
  extend FriendlyId
  friendly_id :parsed_name, use: :slugged
  belongs_to :user

  def parsed_name
    # app.mycreation.ai
    pieces = name.split(".")
    if pieces.size > 2
      pieces[0..-1].join("")
    else
      pieces[0]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected
  def authorized_admin!
    redirect_to root_path if !current_user&.admin?
  end
end

app/controllers/ui_components_controller.rb
class UiComponentsController < ApplicationController
  before_action :authenticate_user!, :authorized_admin!
  before_action :set_ui_component, only: %i[ show edit update destroy ]

  # GET /ui_components or /ui_components.json
  def index
    @ui_components = UiComponent.all
  end

  # GET /ui_components/1 or /ui_components/1.json
  def show
  end

  # GET /ui_components/new
  def new
    @ui_component = UiComponent.new
  end

  # GET /ui_components/1/edit
  def edit
  end

  # POST /ui_components or /ui_components.json
  def create
    @ui_component = UiComponent.new(ui_component_params)

    respond_to do |format|
      if @ui_component.save
        StoreTmpTailwindJob.perform_later(@ui_component.id)
        format.html { redirect_to ui_component_url(@ui_component), notice: "Ui component was successfully created." }
        format.json { render :show, status: :created, location: @ui_component }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ui_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ui_components/1 or /ui_components/1.json
  def update
    respond_to do |format|
      if @ui_component.update(ui_component_params)
        format.html { redirect_to ui_component_url(@ui_component), notice: "Ui component was successfully updated." }
        format.json { render :show, status: :ok, location: @ui_component }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ui_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ui_components/1 or /ui_components/1.json
  def destroy
    @ui_component.destroy!

    respond_to do |format|
      format.html { redirect_to ui_components_url, notice: "Ui component was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ui_component
      @ui_component = UiComponent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ui_component_params
      params.require(:ui_component).permit(:name, :html_content)
    end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_website, only: %i[ show edit update destroy ]

  # GET /websites or /websites.json
  def index
    @websites = current_user.websites.all
    redirect_to new_website_path if @websites.size.zero?
  end

  # GET /websites/1 or /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = current_user.websites.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites or /websites.json
  def create
    @website = current_user.websites.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to website_url(@website), notice: "Website was successfully created." }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1 or /websites/1.json
  def update
    @ui_component = UiComponent.find(params[:ui_component_id])
    @website.html_content = '' if @website.html_content.nil?
    @website.html_content += @ui_component.html_content
    if @website.save
      render turbo_stream: turbo_stream.update("html-content", html: @website.html_content.html_safe)
    end
  end

  # DELETE /websites/1 or /websites/1.json
  def destroy
    @website.destroy!

    respond_to do |format|
      format.html { redirect_to websites_url, notice: "Website was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = current_user.websites.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def website_params
      params.require(:website).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ui_components_helper.rb
module UiComponentsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebsiteBuilder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/ui_components/_form.html.erb
<%= form_with(model: ui_component, class: "contents") do |form| %>
  <% if ui_component.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ui_component.errors.count, "error") %> prohibited this ui_component from being saved:</h2>

      <ul>
        <% ui_component.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :html_content %>
    <%= form.text_area :html_content, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/ui_components/_ui_component.html.erb
<div id="<%= dom_id ui_component %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= ui_component.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Html content:</strong>
    <%= ui_component.html_content %>
  </p>

</div>

app/views/ui_components/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ui component</h1>

  <%= render "form", ui_component: @ui_component %>

  <%= link_to "Show this ui component", @ui_component, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ui components", ui_components_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ui_components/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Ui components" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ui components</h1>
    <%= link_to "New ui component", new_ui_component_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="ui_components" class="min-w-full">
    <% @ui_components.each do |ui_component| %>
      <%= render ui_component %>
      <p>
        <%= link_to "Show this ui component", ui_component, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/ui_components/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ui component</h1>

  <%= render "form", ui_component: @ui_component %>

  <%= link_to "Back to ui components", ui_components_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ui_components/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ui_component %>

    <%= link_to "Edit this ui component", edit_ui_component_path(@ui_component), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to ui components", ui_components_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this ui component", @ui_component, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/websites/_form.html.erb
<%= form_with(model: website, class: "contents") do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
        <% website.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 flex flex-col items-center w-3/4 md:max-w-2xl md:w-full mx-auto">
    <%= form.label :name, "What do you want to call your new website?", class: "text-2xl" %>
    <div class="relative w-full">
      <%= form.text_field :name, class: "block shadow rounded-full border border-gray-400 outline-none px-3 py-2 mt-2 w-full pr-10", placeholder: "thenextbigthing.com" %>
      <div class="absolute right-2 top-3 group"> 
        <%= button_tag type: "submit" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 hover:text-indigo-500">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
          </svg>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/websites/_website.html.erb
<%= link_to website do %>
  <div class="p-2 bg-gray-300 rounded-lg" id="<%= dom_id website %>">
    <p class="my-5 text-xl">
      <%= website.name %>
    </p>
  </div>
<% end %>

app/views/websites/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing website</h1>

  <%= render "form", website: @website %>

  <%= link_to "Show this website", @website, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to websites", websites_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/websites/index.html.erb
<div class="w-full max-w-5xl mx-auto mt-24">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Websites" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Websites</h1>
    <%= link_to "New website", new_website_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="websites" class="min-w-full flex flex-col gap-4 mt-8">
    <% @websites.each do |website| %>
      <%= render website %>
    <% end %>
  </div>
</div>

app/views/websites/new.html.erb
<div class="mx-auto max-w-5xl pb-40 w-full flex flex-col justify-center min-h-screen">
  <h1 class="font-bold text-3xl text-cente hidden">Create Your New Website Now</h1>

  <%= render "form", website: @website %>
</div>

app/views/websites/show.html.erb
<div class="flex" data-controller="drag" data-drag-url-value="<%= website_path(@website) %>" data-drag-param-name-value="ui_component_id"> 
  <div class="w-4/5 min-h-screen" data-action="dragover->drag#allowDrop drop->drag#drop" id="html-content"><%== @website.html_content %></div>
  <div class="w-1/5 bg-gray-300 h-screen fixed right-0 top-0"> 
    <h2 class="text-gray-800 text-center mt-4"> Pick out components </h2>
    <div class="mt-4 grid grid-cols-2 gap-y-8">
      <% UiComponent.all.each do |ui_component| %>
        <div class="flex flex-col items-center hover:bg-gray-100 py-2 cursor-pointer" draggable="true" 
            data-action="dragstart->drag#start" data-drag-data="<%= ui_component.id %>">
          <div class="rounded-lg bg-gray-400 h-24 w-24"> </div>
          <p class="text-center"> <%= ui_component.name %> </p>
        </div>
      <% end %>
    </div>
  </div>
<div>